module.exports.titles = [
    'Da Vinci Code',
    'Harry Potter and the Philosophers stone',
    '1984',
    'Adventures of Huckleberry Finn',
    'The Alchemist',
    'The Aleph and Other Stories',
    'Animal Farm',
    'Aesops Fables',
    'Alices Adventures in Wonderland',
    'Anna Karenina',
    'Anne of Green Gables',
    'As I Lay Dying',
    'Beloved',
    'The Book Thief',
    'Brave New World',
    'The Brothers Karamazov',
    'Catch-22',
    'The Catcher in the Rye',
    'Charlie and the Chocolate Factory',
    'Charlottes Web',
    'The Call of the Wild',
    'A Clockwork Orange',
    'The Code of the Woosters',
    'The Collected of Edgar Allan Po',
    'The Color Purple:',
    'Coraline',
    'The Count of Monte Cristo',
    'Crime and Punishment',
    'The Curious Incident of the Dog in the Night-Time',
    'The Death of Artemio Cruz',
    'Diary of a Madman and Other Stories',
    'The Diary of a Young Girl',
    'The Divine Comedy',
    'Don Quixote',
    'Dracula',
    'Emma',
    'Fahrenheit 451',
    'Frankenstein',
    'The Giver',
    'The Golden Compass ',
    'Goodnight Moon',
    'Great Expectations',
    'The Great Gatsby',
    'Grimms Fairy Tales',
    'Gullivers Travels',
    'Hamlet',
    'The Handmaid Tale',
    'Harry Potter',
    'Heart of Darkness',
    'Here to You, Jesusa!',
    'The Hitchhikers Guide',
    'The Hobbit',
    'Holes',
    'Hopscotch',
    'The Iliad',
    'Invisible Man',
    'Jane Eyre',
    'Journey to the Center of the Earth',
    'Les Miserables',
    'Life of Pi',
    'The Lion, the Witch and the Wardrobe',
    'The little Prince',
    'Little Women',
    'Lolita',
    'The Lord of the Rings',
    'Love in the Time of Cholera',
    'Madame Bovary',
    'Metamorphosis',
    'Moby-Dick',
    'Mrs.Dalloway',
    'Murder on the Orient Express',
    'Of Mice and Men',
    'The Old Man and the Sea',
    'Oliver',
    'One Hundred Years of Solitude',
    'One Thousand and One Nights',
    'A Passage to India',
    'Pedra Paramo',
    'The Phantom Tollbooth',
    'Pippi Longstocking',
    'Pride and Prejudice',
    'The Remains of the Day',
    'Romeo and Juliet',
    'A Series of Unforturnate Events',
    'The Shadow of the Wind',
    'Slaughterhouse-Five',
    'The Sound of the Mountain',
    'The Stranger',
    'The Tale of Genji',
    'Things Fall Apart',
    'The Three Musketeers',
    'To Kill a Mockingbird',
    'Treasure Island',
    'Ulysses',
    'War and Peace',
    'Watership Down',
    'Winnie-the-Pooh',
    'The Woman in white by Wilkie',
    'The Wonderful Wizard of Oz',
    'A Wrinkle in Time',
    'Wuthering HEights',
]